name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: dropdown
    id: effect-version
    attributes:
      label: Effect version
      options:
        - v4 (effect-smol)
        - v3
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Bun 1.3.5, macOS 15.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal code to reproduce the issue.
      render: typescript
    validations:
      required: true
